### ISSUE TITLE
Starting nvim with $GIT_DIR set breaks packer

### ISSUE THREAD

**Issue by loiccoyle** [wbthomason/packer.nvim#465]
- `nvim --version`: NVIM v0.5.0
- `git --version`: git version 2.32.0
- Operating system/version: 5.12.14-arch1-1
- Terminal name/version: alacritty 0.8.0 (a1b13e68)

### Steps to reproduce

```sh
GIT_DIR="some/repo/.git" nvim
```
### Actual behaviour

If the git folder is a bare git folder, `packer` prompts the user to remove all the plugins and then tries and fails to reinstall all the plugins.

If the folder is a "normal" git folder, `packer` freezes `nvim` forcing the user to close the terminal.

### Expected behaviour

`packer` should launch and function as normal.

### packer files

<details>
<summary>Plugin specification file(s)</summary>

```lua
local packer_path = U.os.data .. '/site/pack/packer/opt/packer.nvim'
if vim.fn.empty(vim.fn.glob(packer_path)) > 0 then
  vim.cmd('!git clone https://github.com/wbthomason/packer.nvim ' .. packer_path)
end
vim.cmd 'packadd packer.nvim | au BufWritePost plugins.lua PackerCompile'
vim.opt.rtp = vim.opt.rtp + (U.os.data .. '/site/pack/packer/opt/*')

local packer = require('packer')
local plugin_path = U.os.data .. '/site/pack/packer/opt/'
local packer_compiled = U.os.data .. '/site/plugin/packer_compiled.vim'

return packer.startup(function(use)
  packer.init({compile_path = packer_compiled, opt_default = true})

  -- Plugin Manager
  use {'wbthomason/packer.nvim'}
  -- Autopairs
  use {'windwp/nvim-autopairs', event = 'InsertEnter', config = [[require('plugin.nvim-autopairs')]]}
  -- Buffer Tabs
  use {
    'akinsho/nvim-bufferline.lua',
    setup = [[require('plugin.nvim-bufferline')]],
    requires = {'famiu/bufdelete.nvim'}
  }
  -- Colorizer
  use {'norcalli/nvim-colorizer.lua', event = 'BufEnter', config = [[require('plugin.nvim-colorizer')]]}
  -- Colorschemes
  use {'RRethy/nvim-base16', setup = [[require('plugin.nvim-base16')]]}
  -- Completion
  use {
    {'hrsh7th/nvim-compe', config = [[require('plugin.nvim-compe')]], event = 'InsertEnter'},
    {'hrsh7th/vim-vsnip', requires = {'rafamadriz/friendly-snippets', 'hrsh7th/vim-vsnip-integ'}, event = 'InsertEnter'}
    -- {'tzachar/compe-tabnine', run = './install.sh', requires = 'hrsh7th/nvim-compe'}
  }
  -- Cursors
  use {'xiyaowong/nvim-cursorword', event = 'CursorHold'}
  use {'mg979/vim-visual-multi', event = 'CursorHold', config = [[require('plugin.vim-visual-multi')]]}
  -- Dashboard
  use {'glepnir/dashboard-nvim', setup = [[require('plugin.dashboard-nvim')]]}
  -- File explorer
  use {'kyazdani42/nvim-tree.lua', cmd = 'NVimTreeToggle', setup = [[require('plugin.nvim-tree')]]}
  -- Git
  use {
    'lewis6991/gitsigns.nvim',
    config = [[require('plugin.gitsigns')]],
    requires = {'nvim-lua/plenary.nvim'},
    event = 'BufEnter'
  }
  use {'kdheepak/lazygit.nvim', cmd = 'LazyGit'}
  -- Icons
  use {'kyazdani42/nvim-web-devicons', setup = [[require('plugin.nvim-web-devicons')]]}
  -- Indentline
  use {'lukas-reineke/indent-blankline.nvim', setup = [[require('plugin.indent-blankline')]], event = 'BufEnter'}
  -- Lsp
  -- Lazy loading this can cause issues where no LSP clients are attached.
  use {
    {
      'neovim/nvim-lspconfig',
      setup = [[require('plugin.nvim-lspconfig')]],
      requires = {'kabouzeid/nvim-lspinstall', 'jose-elias-alvarez/nvim-lsp-ts-utils'}
    }, {'ray-x/lsp_signature.nvim'},
    {'kosayoda/nvim-lightbulb', event = 'CursorHold', config = [[require('plugin.nvim-lightbulb')]]},
    {'folke/trouble.nvim', cmd = 'Trouble'}
  }
  -- use {'glepnir/lspsaga.nvim', config = [[require('plugin.lspsaga-nvim')]]}
  -- Profiling
  use {'tweekmonster/startuptime.vim', cmd = 'StartupTime'}
  -- Statusline
  use {
    'glepnir/galaxyline.nvim',
    requires = {'kyazdani42/nvim-web-devicons'},
    config = [[require('plugin.galaxyline')]],
    event = 'BufEnter'
  }
  -- Telescope (requires rg)
  use {
    'nvim-telescope/telescope.nvim',
    setup = [[require('plugin.telescope')]],
    requires = {'nvim-lua/popup.nvim', 'nvim-lua/plenary.nvim', 'nvim-telescope/telescope-fzy-native.nvim'}
    -- lazy loading telescope doesn't load telescope config at the dashboard
    -- config = [[require('plugin.telescope')]],
    -- cmd = 'Telescope'
  }
  -- use {'junegunn/fzf'}
  -- use {'junegunn/fzf.vim'}
  -- Terminal
  -- use {
  --   'akinsho/nvim-toggleterm.lua',
  --   config = [[require('plugin.nvim-toggleterm')]],
  --   keys = '<C-t>'
  -- }
  -- tpope
  use {
    {'tpope/vim-commentary'}, -- Comment with gc
    {'tpope/vim-surround'}, -- Surround actions
    {'tpope/vim-unimpaired'}, -- Adds a bunch of bracket mappings see ':help unimpaired'
    {'tpope/vim-sleuth'}, -- Adapt tab size based on file and context
    {'tpope/vim-repeat'} -- . repeats more stuff
  }
  -- Treesitter
  use {
    'nvim-treesitter/nvim-treesitter',
    run = ':TSUpdate',
    setup = [[require('plugin.nvim-treesitter')]],
    requires = {
      'p00f/nvim-ts-rainbow', 'windwp/nvim-ts-autotag', 'JoosepAlviste/nvim-ts-context-commentstring',
      'nvim-treesitter/nvim-treesitter-textobjects', 'RRethy/nvim-treesitter-textsubjects'
    }
    -- Lazy loading treesitter breaks the highlighting of cursorword
    -- event = 'VimEnter'
  }
  -- Which Key
  use {'folke/which-key.nvim', config = [[require('plugin.which-key')]], event = 'BufEnter'}
  -- Vimwiki
  use {'vimwiki/vimwiki', setup = [[require('plugin.vimwiki')]]}
  -- Zen mode
  use {"Pocco81/TrueZen.nvim", cmd = {'TZAtaraxis', 'TZFocus', 'TZMinimalist'}}
  -- Syntax
  use {'kovetskiy/sxhkd-vim'}
  use {'zinit-zsh/zinit-vim-syntax'}

  -- Autoinstall/compile plugins
  if vim.fn.isdirectory(vim.fn.glob(plugin_path)) > 0 then packer.install() end
  if vim.fn.empty(vim.fn.glob(packer_compiled)) > 0 then packer.compile() end
end)
```
</details>

<details>
<summary>packer log file</summary>

```
[DEBUG Fri 09 Jul 2021 06:12:46 PM CEST 18312390458038] ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:355: packer.install: requiring modules
[DEBUG Fri 09 Jul 2021 06:12:46 PM CEST 18312392165079] ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:302: Processing plugin specs
[DEBUG Fri 09 Jul 2021 06:12:46 PM CEST 18312395942902] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:176: Updating FS state
[DEBUG Fri 09 Jul 2021 06:12:46 PM CEST 18312635956605] ...im/site/pack/packer/opt/packer.nvim/lua/packer/clean.lua:22: Starting clean
[WARN  Fri 09 Jul 2021 06:12:48 PM CEST 18314003717329] ...im/site/pack/packer/opt/packer.nvim/lua/packer/clean.lua:79: Cleaning cancelled!
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314003864184] ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:386: Gathering install tasks
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314020189695] ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:389: Gathering Luarocks tasks
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314020219310] ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:398: Running tasks
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314146980842] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install nvim-lua/plenary.nvim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/plenary.nvim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing nvim-lua/plenary.nvim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/plenary.nvim' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314147292948] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install tweekmonster/startuptime.vim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/startuptime.vim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing tweekmonster/startuptime.vim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/startuptime.vim' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314147531465] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install zinit-zsh/zinit-vim-syntax: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/zinit-vim-syntax' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing zinit-zsh/zinit-vim-syntax: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/zinit-vim-syntax' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314147761726] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install tpope/vim-commentary: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-commentary' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing tpope/vim-commentary: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-commentary' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314148004552] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install hrsh7th/vim-vsnip-integ: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-vsnip-integ' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing hrsh7th/vim-vsnip-integ: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-vsnip-integ' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314148254080] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install windwp/nvim-autopairs: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-autopairs' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing windwp/nvim-autopairs: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-autopairs' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314148466778] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install lewis6991/gitsigns.nvim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/gitsigns.nvim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing lewis6991/gitsigns.nvim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/gitsigns.nvim' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314148664640] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install tpope/vim-sleuth: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-sleuth' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing tpope/vim-sleuth: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-sleuth' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314148859886] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install RRethy/nvim-treesitter-textsubjects: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-treesitter-textsubjects' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing RRethy/nvim-treesitter-textsubjects: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-treesitter-textsubjects' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314149106668] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install kosayoda/nvim-lightbulb: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-lightbulb' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing kosayoda/nvim-lightbulb: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-lightbulb' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314149299941] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install rafamadriz/friendly-snippets: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/friendly-snippets' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing rafamadriz/friendly-snippets: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/friendly-snippets' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314149488194] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install norcalli/nvim-colorizer.lua: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-colorizer.lua' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing norcalli/nvim-colorizer.lua: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-colorizer.lua' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314149651510] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install tpope/vim-repeat: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-repeat' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing tpope/vim-repeat: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-repeat' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314149846305] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install nvim-telescope/telescope.nvim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/telescope.nvim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing nvim-telescope/telescope.nvim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/telescope.nvim' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314150017797] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install akinsho/nvim-bufferline.lua: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-bufferline.lua' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing akinsho/nvim-bufferline.lua: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-bufferline.lua' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314150234153] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install kyazdani42/nvim-web-devicons: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-web-devicons' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing kyazdani42/nvim-web-devicons: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-web-devicons' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314150427094] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install hrsh7th/vim-vsnip: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-vsnip' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing hrsh7th/vim-vsnip: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-vsnip' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314150995420] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install jose-elias-alvarez/nvim-lsp-ts-utils: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-lsp-ts-utils' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing jose-elias-alvarez/nvim-lsp-ts-utils: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-lsp-ts-utils' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314151309780] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install wbthomason/packer.nvim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/packer.nvim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing wbthomason/packer.nvim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/packer.nvim' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314151594594] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install vimwiki/vimwiki: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vimwiki' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing vimwiki/vimwiki: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vimwiki' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314151857366] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install mg979/vim-visual-multi: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-visual-multi' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing mg979/vim-visual-multi: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-visual-multi' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314152144455] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install folke/trouble.nvim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/trouble.nvim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing folke/trouble.nvim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/trouble.nvim' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314152445108] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install famiu/bufdelete.nvim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/bufdelete.nvim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing famiu/bufdelete.nvim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/bufdelete.nvim' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314152739941] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install tpope/vim-surround: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-surround' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing tpope/vim-surround: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-surround' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314152937552] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install hrsh7th/nvim-compe: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-compe' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing hrsh7th/nvim-compe: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-compe' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314153164086] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install kyazdani42/nvim-tree.lua: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-tree.lua' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing kyazdani42/nvim-tree.lua: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-tree.lua' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314153430977] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install p00f/nvim-ts-rainbow: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-ts-rainbow' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing p00f/nvim-ts-rainbow: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-ts-rainbow' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314153641461] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install folke/which-key.nvim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/which-key.nvim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing folke/which-key.nvim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/which-key.nvim' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314153877744] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install kabouzeid/nvim-lspinstall: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-lspinstall' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing kabouzeid/nvim-lspinstall: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-lspinstall' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314154088820] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install neovim/nvim-lspconfig: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-lspconfig' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing neovim/nvim-lspconfig: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-lspconfig' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314154315726] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install windwp/nvim-ts-autotag: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-ts-autotag' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing windwp/nvim-ts-autotag: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-ts-autotag' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314154543332] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install nvim-treesitter/nvim-treesitter-textobjects: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-treesitter-textobjects' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing nvim-treesitter/nvim-treesitter-textobjects: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-treesitter-textobjects' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314154711187] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install kovetskiy/sxhkd-vim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/sxhkd-vim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing kovetskiy/sxhkd-vim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/sxhkd-vim' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314154953732] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install nvim-telescope/telescope-fzy-native.nvim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/telescope-fzy-native.nvim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing nvim-telescope/telescope-fzy-native.nvim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/telescope-fzy-native.nvim' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314155218338] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install RRethy/nvim-base16: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-base16' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing RRethy/nvim-base16: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-base16' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314155441887] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install tpope/vim-unimpaired: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-unimpaired' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing tpope/vim-unimpaired: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-unimpaired' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314155703988] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install nvim-lua/popup.nvim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/popup.nvim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing nvim-lua/popup.nvim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/popup.nvim' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314155968995] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install JoosepAlviste/nvim-ts-context-commentstring: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-ts-context-commentstring' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing JoosepAlviste/nvim-ts-context-commentstring: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-ts-context-commentstring' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314156253669] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install glepnir/dashboard-nvim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/dashboard-nvim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing glepnir/dashboard-nvim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/dashboard-nvim' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314156509789] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install xiyaowong/nvim-cursorword: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-cursorword' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing xiyaowong/nvim-cursorword: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-cursorword' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314156764968] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install Pocco81/TrueZen.nvim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/TrueZen.nvim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing Pocco81/TrueZen.nvim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/TrueZen.nvim' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314156980041] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install glepnir/galaxyline.nvim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/galaxyline.nvim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing glepnir/galaxyline.nvim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/galaxyline.nvim' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314157140271] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install lukas-reineke/indent-blankline.nvim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/indent-blankline.nvim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing lukas-reineke/indent-blankline.nvim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/indent-blankline.nvim' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314157325008] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install nvim-treesitter/nvim-treesitter: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-treesitter' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing nvim-treesitter/nvim-treesitter: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-treesitter' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314157505276] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install ray-x/lsp_signature.nvim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/lsp_signature.nvim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing ray-x/lsp_signature.nvim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/lsp_signature.nvim' already exists and is not an empty directory."
}
[DEBUG Fri 09 Jul 2021 06:12:48 PM CEST 18314158071958] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:26: Failed to install kdheepak/lazygit.nvim: {
  data = { {
      exit_code = 128,
      signal = 0
    }, {
      data = {
        stderr = { "fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/lazygit.nvim' already exists and is not an empty directory." },
        stdout = {}
      },
      err = {
        stderr = {},
        stdout = {}
      }
    } },
  msg = "Error installing kdheepak/lazygit.nvim: fatal: destination path '/home/lcoyle/.local/share/nvim/site/pack/packer/opt/lazygit.nvim' already exists and is not an empty directory."
}
```

</details>

<details>
<summary>packer compiled file</summary>

```
" Automatically generated packer.nvim plugin loader code

if !has('nvim-0.5')
  echohl WarningMsg
  echom "Invalid Neovim version for packer.nvim!"
  echohl None
  finish
endif

packadd packer.nvim

try

lua << END
  local time
  local profile_info
  local should_profile = false
  if should_profile then
    local hrtime = vim.loop.hrtime
    profile_info = {}
    time = function(chunk, start)
      if start then
        profile_info[chunk] = hrtime()
      else
        profile_info[chunk] = (hrtime() - profile_info[chunk]) / 1e6
      end
    end
  else
    time = function(chunk, start) end
  end
  
local function save_profiles(threshold)
  local sorted_times = {}
  for chunk_name, time_taken in pairs(profile_info) do
    sorted_times[#sorted_times + 1] = {chunk_name, time_taken}
  end
  table.sort(sorted_times, function(a, b) return a[2] > b[2] end)
  local results = {}
  for i, elem in ipairs(sorted_times) do
    if not threshold or threshold and elem[2] > threshold then
      results[i] = elem[1] .. ' took ' .. elem[2] .. 'ms'
    end
  end

  _G._packer = _G._packer or {}
  _G._packer.profile_output = results
end

time([[Luarocks path setup]], true)
local package_path_str = "/home/lcoyle/.cache/nvim/packer_hererocks/2.0.5/share/lua/5.1/?.lua;/home/lcoyle/.cache/nvim/packer_hererocks/2.0.5/share/lua/5.1/?/init.lua;/home/lcoyle/.cache/nvim/packer_hererocks/2.0.5/lib/luarocks/rocks-5.1/?.lua;/home/lcoyle/.cache/nvim/packer_hererocks/2.0.5/lib/luarocks/rocks-5.1/?/init.lua"
local install_cpath_pattern = "/home/lcoyle/.cache/nvim/packer_hererocks/2.0.5/lib/lua/5.1/?.so"
if not string.find(package.path, package_path_str, 1, true) then
  package.path = package.path .. ';' .. package_path_str
end

if not string.find(package.cpath, install_cpath_pattern, 1, true) then
  package.cpath = package.cpath .. ';' .. install_cpath_pattern
end

time([[Luarocks path setup]], false)
time([[try_loadstring definition]], true)
local function try_loadstring(s, component, name)
  local success, result = pcall(loadstring(s))
  if not success then
    vim.schedule(function()
      vim.api.nvim_notify('packer.nvim: Error running ' .. component .. ' for ' .. name .. ': ' .. result, vim.log.levels.ERROR, {})
    end)
  end
  return result
end

time([[try_loadstring definition]], false)
time([[Defining packer_plugins]], true)
_G.packer_plugins = {
  ["TrueZen.nvim"] = {
    commands = { "TZAtaraxis", "TZFocus", "TZMinimalist" },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/TrueZen.nvim"
  },
  ["bufdelete.nvim"] = {
    load_after = {
      ["nvim-bufferline.lua"] = true
    },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/bufdelete.nvim"
  },
  ["dashboard-nvim"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/dashboard-nvim"
  },
  ["friendly-snippets"] = {
    load_after = {
      ["vim-vsnip"] = true
    },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/friendly-snippets"
  },
  ["galaxyline.nvim"] = {
    config = { "require('plugin.galaxyline')" },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/galaxyline.nvim"
  },
  ["gitsigns.nvim"] = {
    after = { "plenary.nvim" },
    config = { "require('plugin.gitsigns')" },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/gitsigns.nvim"
  },
  ["indent-blankline.nvim"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/indent-blankline.nvim"
  },
  ["lazygit.nvim"] = {
    commands = { "LazyGit" },
    loaded = false,
    needs_bufread = true,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/lazygit.nvim"
  },
  ["lsp_signature.nvim"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/lsp_signature.nvim"
  },
  ["nvim-autopairs"] = {
    config = { "require('plugin.nvim-autopairs')" },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-autopairs"
  },
  ["nvim-base16"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-base16"
  },
  ["nvim-bufferline.lua"] = {
    after = { "bufdelete.nvim" },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-bufferline.lua"
  },
  ["nvim-colorizer.lua"] = {
    config = { "require('plugin.nvim-colorizer')" },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-colorizer.lua"
  },
  ["nvim-compe"] = {
    after_files = { "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-compe/after/plugin/compe.vim" },
    config = { "require('plugin.nvim-compe')" },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-compe"
  },
  ["nvim-cursorword"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-cursorword"
  },
  ["nvim-lightbulb"] = {
    config = { "require('plugin.nvim-lightbulb')" },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-lightbulb"
  },
  ["nvim-lsp-ts-utils"] = {
    load_after = {
      ["nvim-lspconfig"] = true
    },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-lsp-ts-utils"
  },
  ["nvim-lspconfig"] = {
    after = { "nvim-lspinstall", "nvim-lsp-ts-utils" },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-lspconfig"
  },
  ["nvim-lspinstall"] = {
    load_after = {
      ["nvim-lspconfig"] = true
    },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-lspinstall"
  },
  ["nvim-tree.lua"] = {
    commands = { "NVimTreeToggle" },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-tree.lua"
  },
  ["nvim-treesitter"] = {
    after = { "nvim-ts-context-commentstring", "nvim-treesitter-textobjects", "nvim-ts-autotag", "nvim-ts-rainbow", "nvim-treesitter-textsubjects" },
    loaded = false,
    needs_bufread = true,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-treesitter"
  },
  ["nvim-treesitter-textobjects"] = {
    load_after = {
      ["nvim-treesitter"] = true
    },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-treesitter-textobjects"
  },
  ["nvim-treesitter-textsubjects"] = {
    load_after = {
      ["nvim-treesitter"] = true
    },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-treesitter-textsubjects"
  },
  ["nvim-ts-autotag"] = {
    load_after = {
      ["nvim-treesitter"] = true
    },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-ts-autotag"
  },
  ["nvim-ts-context-commentstring"] = {
    load_after = {
      ["nvim-treesitter"] = true
    },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-ts-context-commentstring"
  },
  ["nvim-ts-rainbow"] = {
    load_after = {
      ["nvim-treesitter"] = true
    },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-ts-rainbow"
  },
  ["nvim-web-devicons"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/nvim-web-devicons"
  },
  ["packer.nvim"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/packer.nvim"
  },
  ["plenary.nvim"] = {
    load_after = {
      ["gitsigns.nvim"] = true
    },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/plenary.nvim"
  },
  ["popup.nvim"] = {
    load_after = {
      ["telescope.nvim"] = true
    },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/popup.nvim"
  },
  ["startuptime.vim"] = {
    commands = { "StartupTime" },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/startuptime.vim"
  },
  ["sxhkd-vim"] = {
    loaded = false,
    needs_bufread = true,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/sxhkd-vim"
  },
  ["telescope-fzy-native.nvim"] = {
    load_after = {
      ["telescope.nvim"] = true
    },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/telescope-fzy-native.nvim"
  },
  ["telescope.nvim"] = {
    after = { "popup.nvim", "telescope-fzy-native.nvim" },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/telescope.nvim"
  },
  ["trouble.nvim"] = {
    commands = { "Trouble" },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/trouble.nvim"
  },
  ["vim-commentary"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-commentary"
  },
  ["vim-repeat"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-repeat"
  },
  ["vim-sleuth"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-sleuth"
  },
  ["vim-surround"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-surround"
  },
  ["vim-unimpaired"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-unimpaired"
  },
  ["vim-visual-multi"] = {
    config = { "require('plugin.vim-visual-multi')" },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-visual-multi"
  },
  ["vim-vsnip"] = {
    after = { "friendly-snippets", "vim-vsnip-integ" },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-vsnip"
  },
  ["vim-vsnip-integ"] = {
    after_files = { "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-vsnip-integ/after/plugin/vsnip_integ.vim" },
    load_after = {
      ["vim-vsnip"] = true
    },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vim-vsnip-integ"
  },
  vimwiki = {
    loaded = false,
    needs_bufread = true,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/vimwiki"
  },
  ["which-key.nvim"] = {
    config = { "require('plugin.which-key')" },
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/which-key.nvim"
  },
  ["zinit-vim-syntax"] = {
    loaded = false,
    needs_bufread = false,
    path = "/home/lcoyle/.local/share/nvim/site/pack/packer/opt/zinit-vim-syntax"
  }
}

time([[Defining packer_plugins]], false)
-- Setup for: nvim-bufferline.lua
time([[Setup for nvim-bufferline.lua]], true)
require('plugin.nvim-bufferline')
time([[Setup for nvim-bufferline.lua]], false)
-- Setup for: nvim-treesitter
time([[Setup for nvim-treesitter]], true)
require('plugin.nvim-treesitter')
time([[Setup for nvim-treesitter]], false)
-- Setup for: nvim-web-devicons
time([[Setup for nvim-web-devicons]], true)
require('plugin.nvim-web-devicons')
time([[Setup for nvim-web-devicons]], false)
-- Setup for: indent-blankline.nvim
time([[Setup for indent-blankline.nvim]], true)
require('plugin.indent-blankline')
time([[Setup for indent-blankline.nvim]], false)
-- Setup for: telescope.nvim
time([[Setup for telescope.nvim]], true)
require('plugin.telescope')
time([[Setup for telescope.nvim]], false)
-- Setup for: nvim-lspconfig
time([[Setup for nvim-lspconfig]], true)
require('plugin.nvim-lspconfig')
time([[Setup for nvim-lspconfig]], false)
-- Setup for: nvim-base16
time([[Setup for nvim-base16]], true)
require('plugin.nvim-base16')
time([[Setup for nvim-base16]], false)
-- Setup for: nvim-tree.lua
time([[Setup for nvim-tree.lua]], true)
require('plugin.nvim-tree')
time([[Setup for nvim-tree.lua]], false)
-- Setup for: dashboard-nvim
time([[Setup for dashboard-nvim]], true)
require('plugin.dashboard-nvim')
time([[Setup for dashboard-nvim]], false)
-- Setup for: vimwiki
time([[Setup for vimwiki]], true)
require('plugin.vimwiki')
time([[Setup for vimwiki]], false)

-- Command lazy-loads
time([[Defining lazy-load commands]], true)
vim.cmd [[command! -nargs=* -range -bang -complete=file TZMinimalist lua require("packer.load")({'TrueZen.nvim'}, { cmd = "TZMinimalist", l1 = <line1>, l2 = <line2>, bang = <q-bang>, args = <q-args> }, _G.packer_plugins)]]
vim.cmd [[command! -nargs=* -range -bang -complete=file TZAtaraxis lua require("packer.load")({'TrueZen.nvim'}, { cmd = "TZAtaraxis", l1 = <line1>, l2 = <line2>, bang = <q-bang>, args = <q-args> }, _G.packer_plugins)]]
vim.cmd [[command! -nargs=* -range -bang -complete=file NVimTreeToggle lua require("packer.load")({'nvim-tree.lua'}, { cmd = "NVimTreeToggle", l1 = <line1>, l2 = <line2>, bang = <q-bang>, args = <q-args> }, _G.packer_plugins)]]
vim.cmd [[command! -nargs=* -range -bang -complete=file LazyGit lua require("packer.load")({'lazygit.nvim'}, { cmd = "LazyGit", l1 = <line1>, l2 = <line2>, bang = <q-bang>, args = <q-args> }, _G.packer_plugins)]]
vim.cmd [[command! -nargs=* -range -bang -complete=file StartupTime lua require("packer.load")({'startuptime.vim'}, { cmd = "StartupTime", l1 = <line1>, l2 = <line2>, bang = <q-bang>, args = <q-args> }, _G.packer_plugins)]]
vim.cmd [[command! -nargs=* -range -bang -complete=file TZFocus lua require("packer.load")({'TrueZen.nvim'}, { cmd = "TZFocus", l1 = <line1>, l2 = <line2>, bang = <q-bang>, args = <q-args> }, _G.packer_plugins)]]
vim.cmd [[command! -nargs=* -range -bang -complete=file Trouble lua require("packer.load")({'trouble.nvim'}, { cmd = "Trouble", l1 = <line1>, l2 = <line2>, bang = <q-bang>, args = <q-args> }, _G.packer_plugins)]]
time([[Defining lazy-load commands]], false)

vim.cmd [[augroup packer_load_aucmds]]
vim.cmd [[au!]]
  -- Event lazy-loads
time([[Defining lazy-load event autocommands]], true)
vim.cmd [[au CursorHold * ++once lua require("packer.load")({'nvim-cursorword', 'vim-visual-multi', 'nvim-lightbulb'}, { event = "CursorHold *" }, _G.packer_plugins)]]
vim.cmd [[au InsertEnter * ++once lua require("packer.load")({'nvim-compe', 'vim-vsnip', 'nvim-autopairs'}, { event = "InsertEnter *" }, _G.packer_plugins)]]
vim.cmd [[au BufEnter * ++once lua require("packer.load")({'indent-blankline.nvim', 'galaxyline.nvim', 'which-key.nvim', 'nvim-colorizer.lua', 'gitsigns.nvim'}, { event = "BufEnter *" }, _G.packer_plugins)]]
time([[Defining lazy-load event autocommands]], false)
vim.cmd("augroup END")
if should_profile then save_profiles() end

END

catch
  echohl ErrorMsg
  echom "Error in packer_compiled: " .. v:exception
  echom "Please check your config for correctness"
  echohl None
endtry
```
</details>

**Comment by wbthomason** [comment]
Thanks for the report! This is an interesting bug. I suspect we need to strip `GIT_DIR` out of the environment we pass to the `git` commands we run; I don't think this will break any legitimate use cases?

**Comment by wbthomason** [comment]
@loiccoyle Could you please test #466 and see if it fixes the issue for you?

**Comment by loiccoyle** [comment]
I changed the bootstrap git clone command to :
```lua
vim.cmd('!git clone https://github.com/wbthomason/packer.nvim --branch="fix/remove-git-dir-from-env" ' .. packer_path)
```
And deleted my packer folder. It doesn't seem to fix it though :(.

**Comment by wbthomason** [comment]
Ah, that's totally my bad - I was in too much of a hurry and neglected to ensure we use the right environment for **all** git commands, not just installs.

I've pushed another commit to that branch, if you'd like to try it out. It fixes the issue on my end.

**Comment by wbthomason** [comment]
Also, for the future: if you want to try out a PR branch, you can just pull the repo manually and checkout the corresponding branch (at least, if it's a branch on this repo and not someone else's fork). This is a bit easier than re-cloning every time.

**Comment by loiccoyle** [comment]
No worries, it does indeed fix the issue of the bare git repo issue.

I still get some werid behaviour when I set GIT_DIR to a "normal" .git folder, nvim hangs a long time at statup ~10s, then everything works as expected.

**Comment by wbthomason** [comment]
Interesting. I'm not sure if that's `packer` - we do nothing with `git` unless you're running an install or update operation.

**Comment by loiccoyle** [comment]
Yeah you are right, I tried disabling plugins and the issue goes away if I get rid of `nvim-tree`.

**Comment by loiccoyle** [comment]
Thanks a lot for the quick response and fix !
